---
services:
  - docker:dind

test py37: &default_def
  image: pycontribs/centos:8
  variables:
    TOXENV: py37
  script:
    - tox

#test py38:
#  <<: *default_def
#  image: python:3.8-buster
#  variables:
#    TOXENV: py38
#  before_script:
#    - apt-get -qq update
#    - apt-get install -y bash bats netcat grep tox python-pip

# vim:sw=2:ts=2:et:
