---
# yamllint disable-line rule:line-length
# Based on https://github.com/Azure-Samples/azure-pipelines-python/blob/master/.azure-pipelines/simple_package.1-multi-target.yml
# another ref. https://github.com/tox-dev/azure-pipelines-template
variables:
  package: ansible-role-simple-httpd-example
  srcDirectory: src/$(package)
  testsDirectory: tests/$(package)

trigger:
  branches:
    include:
      - '*'

jobs:
  - job: Build
    strategy:
      matrix:
        python36:
          pythonVersion: 3.6
        python37:
          pythonVersion: 3.7
        python38:
          pythonVersion: 3.8
        python39:
          pythonVersion: 3.9
        python36-ansible29:
          pythonVersion: 3.6
          subVer: -ansible29

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      # yamllint disable-line rule:line-length
      TOXENV: py${{ replace(variables.pythonVersion, '.', '') }}${{ variables.subVer }}

    steps:
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)

      - script: |
          sudo apt-get install -y bash bats iproute2 ansible-lint yamllint
        displayName: Install test time dependencies

      - script: |
          python -m pip install --upgrade pip
          pip install tox
        displayName: Install some more test time dependencies

      - bash: tox -e $TOXENV
        displayName: Run tests

# vim:sw=2:ts=2:et:
