---
# .. note:: These are just example confgiurations.
- name: "Ensure www server will listen on the port {{ sshe_httpd_port }}"
  lineinfile:
    path: >-
      {{ sshe_httpd_configs.0.path }}
    line: >-
      Listen {{ sshe_httpd_port }}
    create: true
    mode: 0644
  when:
    - os_family == 'RedHat'

- name: Ensure www server is configured as expected
  lineinfile:
    path: >-
      {{ sshe_httpd_configs.0.path }}
    line: >-
      ServerName localhost:{{ sshe_httpd_port }}
    insertafter: ^#ServerName
    mode: 0644

# .. note:: handler is not used to simplify it
- name: Ensure www server system service is started
  block:
    - name: Ensure www service system service is enabled and started
      systemd:
        name: "{{ sshe_httpd_service }}"
        state: started
        enabled: true
        daemon_reload: true
      register: __result
  rescue:
    - name: Try to dump the configuration updateded
      debug:
        msg: |
          {{ lookup('file', sshe_httpd_configs.0.path) }}
      changed_when: false

    - name: Try to get the status of the service
      command: >-
        systemctl status {{ sshe_httpd_service }}
      ignore_errors: true
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Print errors
      ansible.builtin.debug:
        var: __result

# vim:sw=2:ts=2:et:
