---
# .. note:: These are just example confgiurations.
- name: "Ensure www server will listen on the port {{ sshe_httpd_port }}"
  lineinfile:
    path: >-
      {{ sshe_httpd_configs.0.path }}
    line: >-
      Listen {{ sshe_httpd_port }}
    create: true
    mode: 0644

- name: Ensure www server is configured as expected
  lineinfile:
    path: >-
      {{ sshe_httpd_configs.0.path }}
    line: >-
      ServerName localhost:{{ sshe_httpd_port }}
    insertafter: ^#ServerName
    mode: 0644

# .. note:: handler is not used to simplify it
- name: Ensure www server system service is enabled and started
  systemd:
    name: "{{ sshe_httpd_service }}"
    state: started
    enabled: true
    # daemon_reload: true

# vim:sw=2:ts=2:et:
