---
# .. note:: These are just example confgiurations.
- name: Ensure custom configurations were added as intended
  ansible.builtin.blockinfile:
    path: >-
      {{ item.path }}
    block: |
      {{ item.block }}
    mode: 0644
    create: >-
      {{ item.create | d(false) }}
    insertafter: >-
      {{ item.insertafter | d('EOF') }}
  loop: "{{ sshe_httpd_configs }}"

# .. note:: handler is not used to simplify its implementation.
- name: Ensure www server system service is started and enabled
  block:
    - name: Ensure www service system service is enabled and started
      ansible.builtin.systemd:
        name: "{{ sshe_httpd_service }}"
        state: started
        enabled: true
        daemon_reload: true
      register: __result
  rescue:
    - name: Try to dump the configuration updateded
      ansible.builtin.debug:
        msg: |
          {{ lookup('file', item.path) }}
      changed_when: false
      loop: "{{ sshe_httpd_configs }}"

    - name: Try to get the status of the service
      ansible.builtin.command: >-
        systemctl status {{ sshe_httpd_service }}
      ignore_errors: true
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Print errors
      ansible.builtin.debug:
        var: __result
