---
# .. note:: These are just example confgiurations.
- name: "Ensure www server is listening on the port {{ sshe_httpd_port }}"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: Listen 80

- name: Ensure www server is configured as expected
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: ServerName localhost:80
    insertafter: ^#ServerName

# .. note:: handler is not used to simplify it
- name: Ensure www server system service is enabled and started
  systemd:
    name: "{{ sshe_httpd_service }}"
    state: started
    enabled: true
# .. todo:: Requires root mode?
#    daemon_reload: true

# vim:sw=2:ts=2:et:
