---
- name: Test variables are OK
  ansible.builtin.assert:
    that:
      - sshe_httpd_pkg | length > 0
      - sshe_httpd_service | length > 0
      - sshe_verification_pkgs | select('==', '""') | length == 0
    fail_msg: |
      sshe_httpd_pkg: {{ sshe_httpd_pkg }}
      sshe_httpd_service: {{ sshe_httpd_service }}
      sshe_verification_pkgs: {{ sshe_verification_pkgs | to_nice_json }}

- name: Test other complex checks for variables
  block:
    - name: Test the variable 'sshe_httpd_configs' has expected values
      ansible.builtin.assert:
        that:
          - >-
            sshe_httpd_configs | selectattr('path', '==', '""')
                               | length == 0
          - >-
            sshe_httpd_configs | selectattr('block', '==', '""')
                               | length == 0
        fail_msg: |
          sshe_httpd_configs: {{ sshe_httpd_configs | to_nice_json }}
      when:
        - sshe_httpd_configs | length > 0
