---
- name: Test if the given package is installed
  ansible.builtin.command: >-
    dpkg --status {{ sshe_httpd_pkg }}
  register: __result
  changed_when: false
  failed_when:
    - __result.rc != 0
