---
# Configuration and health check examples
#
- name: Test if the system service is enabled
  command: >-
    systemctl is-enabled {{ sshe_httpd_service }}
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Test if the system service is running
  command: >-
    systemctl is-active {{ sshe_httpd_service }}
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Test if the system service is listening on the port
  command: >-
    nc -z localhost {{ sshe_httpd_port }}
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Test if the system service is configured as expected
  command: >-
    grep -q '{{ item.pattern }}' {{ item.path }}
  changed_when: false
  become: true
  tags:
    - skip_ansible_lint
  loop: "{{ sshe_httpd_configs }}"

# vim:sw=2:ts=2:et:
