---
# Configuration and health check examples
#
- name: Test if the given package is installed
  ansible.builtin.command: >-
    rpm -q {{ sshe_httpd_pkg }}
  register: __result
  changed_when: false
  failed_when:
    - __result.rc != 0
