---
# Configuration and health check examples
#
- name: Test if the system service is enabled
  ansible.builtin.command: >-
    systemctl is-enabled {{ sshe_httpd_service }}
  register: __result
  changed_when: false
  failed_when:
    - __result.rc != 0

- name: Test if the system service is running
  ansible.builtin.command: >-
    systemctl is-active {{ sshe_httpd_service }}
  register: __result
  changed_when: false
  failed_when:
    - __result.rc != 0

- name: Test if a client can fetch a content
  ansible.builtin.uri:
    url: "http://localhost/"
    return_content: true
    status_code:
      - 200
      - 403
      - 404
    timeout: 5
  register: __result
  failed_when:
    - not(__result.content)

# fixme:
- name: Test if the system service is configured as expected
  ansible.builtin.command: >-
    grep -q '{{ item.block | list | first }}' {{ item.path }}
  register: __result
  changed_when: false
  failed_when:
    - __result.rc != 0
  loop: "{{ sshe_httpd_configs }}"
