---
# www server's package name, httpd or nginx for example.
sshe_httpd_pkg: >-
  {{ 'httpd' if os_family == 'RedHat' else 'apache2' }}

# www server's service name, same as the package name by default.
sshe_httpd_service: "{{ sshe_httpd_pkg }}"

# www server's configuration files to modify or create.
#
# parameters:
# - path: Configuration file path
# - block: Block of configuration text
# - insertafter: Regex pattern to search to add block text after [EOF]
# - create: Create a new file if it does not exist [false]
#
# .. seealso:: molecule/default/group_vars/all.yml
sshe_httpd_configs: []
