---
# www server's package name, httpd or nginx for example.
sshe_httpd_pkg: >-
  {{ 'httpd' if os_family == 'RedHat' else 'apache2' }}

# www server's service name, same as the package name by default.
sshe_httpd_service: "{{ sshe_httpd_pkg }}"

# HTTP listening port of the wwww server
sshe_httpd_port: 80

# www server's configuration files and (regexp) patterns in them to match.
#
sshe_httpd_configs:
  - path: >-
      {{ '/etc/httpd/conf/httpd.conf'
         if os_family == 'RedHat'
         else '/etc/apache2/sites-available/000-default.conf' }}

    pattern: ServerName localhost

# vim:sw=2:ts=2:et:
