---
- name: Destroy the instance for testing
  hosts: all
  connection: local
  gather_facts: true
  become: true
  vars:
    sshe_httpd_service: >-
      {{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}
  tasks:
    - name: Test if www server system service is found
      command: "systemctl status {{ sshe_httpd_service }}"
      ignore_errors: true
      register: svc_is_found

    - name: Ensure www server system service is disabled and stopped
      systemd:
        name: "{{ sshe_httpd_service }}"
        state: stopped
        enabled: false
      when:
        - svc_is_found.rc in [0, 3]

# vim:sw=2:ts=2:et:
