---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
# https://hub.docker.com/_/centos/
platforms:
  - name: centos-systemd
    # name: ubi8-init
    # image: registry.access.redhat.com/ubi8-init:latest
    # image: ubi8-init:latest
    image: centos/systemd

    # .. note::
    #    It seems that followings are not needed.
    #    - https://github.com/projectatomic/oci-systemd-hook
    #
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    command: /sbin/init
    env:
      oci-systemd-hook: disabled

provisioner:
  name: ansible
  # .. todo::
  # env:
  #   ANSIBLE_ROLES_PATH: ../../
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sshe_verification_mode: false
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint

# vim:sw=2:ts=2:et:
