---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
# https://hub.docker.com/_/centos/
platforms:
  - name: centos-systemd
    # name: ubi8-init
    # image: registry.access.redhat.com/ubi8-init:latest
    # image: ubi8-init:latest
    image: centos/systemd
    privileged: true  # To use systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /sbin/init

provisioner:
  name: ansible
  # .. todo::
  # env:
  #   ANSIBLE_ROLES_PATH: ../../
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sshe_verification_mode: false
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint

# vim:sw=2:ts=2:et:
