---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
# https://hub.docker.com/_/centos/
platforms:
  - name: centos-7
    image: centos:7
provisioner:
  name: ansible
  # .. todo::
  # env:
  #   ANSIBLE_ROLES_PATH: ../../
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sshe_verification_mode: false
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: flake8

# vim:sw=2:ts=2:et:
