---
dependency:
  name: galaxy

lint:
  name: yamllint

# yamllint disable-line rule:line-length
# .. seealso:: https://molecule.readthedocs.io/en/stable/configuration.html#delegated
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: instance-localhost

provisioner:
  name: ansible
  # .. todo::
  # env:
  #   ANSIBLE_ROLES_PATH: ../../
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sshe_verification_mode: false
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint

# vim:sw=2:ts=2:et:
