---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -c molecule/yamllint.cfg .
  ansible-lint -c molecule/dot.ansible-lint .
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance-localhost
provisioner:
  name: ansible
  options:
    vv: true
    become: true
  inventory:
    links:
      group_vars: group_vars/
verifier:
  name: ansible
  options:
    become: true
  inventory:
    links:
      group_vars: group_vars/
