---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -c molecule/yamllint.cfg .
  ansible-lint -c molecule/dot.ansible-lint .
driver:
  name: podman
# https://molecule.readthedocs.io/en/latest/examples.html#systemd-container
platforms:
  - name: instance
    # Other alternatives:
    #   - docker.io/ssato/fedora-python-systemd:36
    #
    image: docker.io/ssato079/centos-stream-python-systemd:8
    pre_build_image: true
    command: /sbin/init
    # capabilities:
    #  - SYS_ADMIN
    # priviledged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:8080:80/tcp
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    links:
      group_vars: group_vars/
verifier:
  name: ansible
  inventory:
    links:
      group_vars: group_vars/
