---
# .. seealso:: https://github.com/ymyzk/tox-gh-actions
#
name: Tests using docker image
# yamllint disable-line rule:truthy
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install required debs
        run: sudo apt-get install -y bash bats tox iproute2 iputils-ping
      - name: Install dependencies
        run: pip install tox-gh-actions
      - name: Test with tox
        run: tox -e docker

# vim:sw=2:ts=2:et:
